#import "../xwysyy.typ": *

#let selected-theme = sys.inputs.at("theme", default: "sky")
#let visual-ci = sys.inputs.at("visual-ci", default: "false") == "true"
#let visual-font = if visual-ci { ("Liberation Serif", "Noto Serif CJK SC") } else { ("Times New Roman", "Noto Serif CJK SC") }
#let visual-code-font = if visual-ci { ("DejaVu Sans Mono", "Noto Sans Mono CJK SC") } else { ("Maple Mono", "Noto Sans Mono CJK SC") }
#let visual-date = if visual-ci { datetime(year: 2026, month: 7, day: 10) } else { datetime.today() }

#show: xwysyy-pre.with(
  theme: selected-theme,
  font: visual-font,
  code-font: visual-code-font,
  config-info(
    title: [xwysyy theme preview],
    subtitle: [#selected-theme],
    author: " ",
    date: visual-date,
    institution: " ",
  ),
)

#title-slide()

#outline-slide()

= Theme Surface

== Components

This page checks header, table, textbox, code, list markers, and the outline badge for one theme.

#textbox(
  [*Primary surface*

  Links use the theme main color. See #link("https://typst.app")[Typst].],
  [*Highlights*

  #red[Red] and #yellow[yellow] helpers remain theme-independent.],
)

#v(0.4em)

#figure(
  table(
    columns: (auto, auto, auto),
    [Item], [Role], [Status],
    [Header], [Theme color], [Checked],
    [Textbox], [Light fill], [Checked],
    [Code], [Light fill], [Checked],
  ),
  caption: [Theme color surface check],
)

```typst
#show: xwysyy-pre.with(theme: selected-theme)
```

#end-slide(body: [Generated by examples/theme-preview.typ])
